version: build{build}
image: Visual Studio 2017
#clone_folder: C:\CK-World\SimpleGitVersion\CodeCake
#branches:
#  only:
#    - master
#    - develop
environment:
  MYGET_CI_API_KEY:
    secure: w9TR+h+r5ZTPdqedGkiqoekB3DKzkXqiqvAITYn2p+Vej2mp9ZBpy4T3LvSR1sbE
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
services:
  - mssql2017