version: build{build}
image: Visual Studio 2017

environment:
  ConnectionStrings_SuperstarsDB: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!

build_script:
  - dotnet run --project src\CodeCakeBuilder -nointeraction

test: off

services:
  - mssql2017

