version: build{build}
image: Visual Studio 2017
#clone_folder: C:\CK-World\SimpleGitVersion\CodeCake
#branches:
#  only:
#    - master
#    - develop
environment:
  ConnectionStrings_SuperstarsDB: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!


build_script:
  - dotnet run --project src\CodeCakeBuilder -nointeraction
test: off
services:
  - mssql2017

artifacts:
- path: DB.zip
  name: DB

- path: WebApp.zip
  name: WebApp

deploy:
- provider: Octopus
  push_packages: true
  create_release: false
  deploy_release: false
  server: http://octo.francecentral.cloudapp.azure.com
  api_key: 
    secure: EwWTXSmLE6eDoBq6XaWyNzzMEgr8H0bYk9RkVXMRxms=
  project: All'in
  