version: build{build}
image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }

environment:
  ConnectionStrings_SuperstarsDB: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!

build_script:
  - dotnet run --project src\CodeCakeBuilder -nointeraction

test: off

services:
  - mssql2017

artifacts:
- path: '**\*.zip'

deploy:
- provider: Octopus
  push_packages: true
  create_release: true
  deploy_release: true
  server: http://octo.francecentral.cloudapp.azure.com
  api_key: 
    secure: EwWTXSmLE6eDoBq6XaWyNzzMEgr8H0bYk9RkVXMRxms=
  project: All'in
  version: $env:APPVEYOR_REPO_TAG_NAME
  deployat: 22:00:00
  on:
   appveyor_repo_tag: true  
  
  