version: build{build}
image: Visual Studio 2017
#clone_folder: C:\CK-World\SimpleGitVersion\CodeCake
#branches:
#  only:
#    - master
#    - develop
environment:
  ConnectionStrings_SuperstarsDB: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!


build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
services:
  - mssql2017